import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


const merriweather = Merriweather({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-merriweather" });


export const metadata: Metadata = {
  title: "A Rishab Agarwala | Chartered Accountant in Guwahati, Assam",
  description: "Generated by create next app",
  keywords: ["A Rishab Agarwala", "Chartered Accountant", "Guwahati", "Assam"],
  authors: [{ name: "A Rishab Agarwala", url: "https://rishabagarwala.com" }],
  creator: "A Rishab Agarwala",
  publisher: "A Rishab Agarwala",
  openGraph: {
    title: "A Rishab Agarwala | Chartered Accountant in Guwahati, Assam",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen ${merriweather.variable} ${merriweather.variable} antialiased`}
      >
        <Navbar />
          <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
